
apiVersion: v1
kind: Service
metadata:
  name: subscription
spec:
  type: LoadBalancer
  selector:
    app: subscription
  ports:
    - name: subscription
      port: 9003
      targetPort: 9003
      nodePort: 30017
