
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - name: server
      port: 5672
      targetPort: 5672
      nodePort: 30001
    - name: management
      port: 15672
      targetPort: 15672
      nodePort: 30002
