{
 "title": "🦧monos-market-place",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "resolution",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "DS_INFLUX", "query": "influx" }
  ]
 },
 "panels": [
  {
   "title": "Router Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "router",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
     ]
    }
   ]
  },
  {
   "title": "Proxy Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "layer", "operator": "=", "value": "pipe" }
     ]
    }
   ]
  },
  {
   "title": "Backend Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "layer", "operator": "=", "value": "backend" }
     ]
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "ns",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "router.response-time",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time stddev",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "ns",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "router.response-time",
     "select": [
      [
       { "params": [ "stddev" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "ns",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "router.response-time",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocated Mem (per host)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "MemStats.Alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Goroutines (per host)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "NumGoroutine" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Router", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Endpoint Throughput (per $resolution)",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "$tag_status $tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "responses",
     "query": "SELECT mean(\"count\") FROM \"responses\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($resolution), \"name\", \"status\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Endpoint Response Time (per $resolution)",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.response-time",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Connections per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "open",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "router",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
     ]
    },
    {
     "alias": "closed",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "router",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "out" }
     ]
    }
   ]
  },
  {
   "title": "Response Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_status",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "responses",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.response-time",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time HeatMap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "router.response-time",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.response-size",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Size HeatMap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "router.response-size",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Router connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "open",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "router",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "direction", "operator": "=", "value": "in" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "close",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "router",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "direction", "operator": "=", "value": "out" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Router response",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_status",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "responses",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Pipe Throughput (per $resolution)",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "SELECT mean(\"count\") FROM \"requests\" WHERE (\"layer\" = 'pipe') AND $timeFilter GROUP BY \"name\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "pipe" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Pipe Response Time (per $resolution)",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "pipe" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Proxy Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "pipe" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Proxy response distribution (per $resolution)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "pipe" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Proxy Timers (ok)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "pipe" },
      { "condition": "AND", "key": "error", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "complete", "operator": "=", "value": "true" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "OK Request HeatMap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "pipe" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "complete", "operator": "=", "value": "true" },
      { "condition": "AND", "key": "error", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Proxy Timers (incomplete)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "pipe" },
      { "condition": "AND", "key": "complete", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Incomplete Request HeatMap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "pipe" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "complete", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Backend Throughput (per $resolution)",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "SELECT mean(\"count\") FROM \"requests\" WHERE (\"layer\" = 'backend') AND $timeFilter GROUP BY \"name\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "backend" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend Response Time (per $resolution)",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "backend" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "backend" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend response distribution (per $resolution)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "c: $tag_complete, e: $tag_error",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "complete" ], "type": "tag" },
      { "params": [ "error" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "backend" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend Timers (ok)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "backend" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "OK Request HeatMap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "backend" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "error", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "complete", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Backend Timers (incomplete)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "backend" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "complete", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Incomplete Request HeatMap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "backend" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "complete", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "NumGoroutine" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "NumThread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "GC Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "debug",
     "select": [
      [
       { "params": [ "GCStats.PauseTotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "pause" ], "type": "alias" }
      ],
      [
       { "params": [ "GCStats.NumGC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "executions" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "GC Spread",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 134 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "debug",
     "select": [
      [
       { "params": [ "GCStats.PauseTotal" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "pause" ], "type": "alias" }
      ],
      [
       { "params": [ "GCStats.NumGC" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "executions" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "GC Pause",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 134 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "service.debug.GCStats.Pause",
     "query": "SELECT max(\"max\") AS \"max\" FROM \"service.debug.GCStats.Pause\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($resolution) fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ],
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min" ], "type": "alias" }
      ],
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mean" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocated Mem",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "sum",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "MemStats.Alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Sys (bytes obtained from system)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 143 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "MemStats.Sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Sys" ], "type": "alias" }
      ],
      [
       { "params": [ "MemStats.HeapSys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "HeapSys" ], "type": "alias" }
      ],
      [
       { "params": [ "MemStats.StackSys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "StackSys" ], "type": "alias" }
      ],
      [
       { "params": [ "MemStats.MCacheSys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "MCacheSys" ], "type": "alias" }
      ],
      [
       { "params": [ "MemStats.MSpanSys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "MSpanSys" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Stack Management",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "MemStats.StackInuse" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "StackInUse" ], "type": "alias" }
      ],
      [
       { "params": [ "MemStats.StackSys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "StackSys" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Heap Management",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 152 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "MemStats.HeapInuse" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "HeapInuse" ], "type": "alias" }
      ],
      [
       { "params": [ "MemStats.HeapSys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "HeapSys" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Idle Memory",
   "type": "graph",
   "description": "HeapIdle minus HeapReleased estimates the amount of memory that could be returned to the OS, but is being retained by the runtime so it can grow the heap without requesting more memory from the OS. If this difference is significantly larger than the heap size, it indicates there was a recent transient spike in live heap size.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "MemStats.HeapIdle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "HeapIdle" ], "type": "alias" }
      ],
      [
       { "params": [ "MemStats.HeapReleased" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "HeapReleased" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Heap Alloc vs InUse",
   "type": "graph",
   "description": "HeapInuse minus HeapAlloc estimates the amount of memory that has been dedicated to particular size classes, but is not currently being used. This is an upper bound on fragmentation, but in general this memory can be reused efficiently.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 161 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "MemStats.HeapAlloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "HeapAlloc" ], "type": "alias" }
      ],
      [
       { "params": [ "MemStats.HeapInuse" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "HeapInuse" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Pointer Lookups",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 170 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "sum",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "MemStats.Lookups" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Management",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 170 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "select": [
      [
       { "params": [ "MemStats.Mallocs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "MALLOCS" ], "type": "alias" }
      ],
      [
       { "params": [ "MemStats.Frees" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "FREE" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}