
apiVersion: apps/v1
kind: Deployment
metadata:
  name: branch
spec:
  selector:
    matchLabels:
      app: branch
  template:
    metadata:
      labels:
        app: branch
    spec:
      containers:
      - name: branch
        image: monos-market-place/branch:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9004
